name: ci_test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: test
        run: 'npm i --silent'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.7.2
      - name: test
        run: npm run test 
          
