name: ci_test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: test
        run: 'npm i --silent'
      - name: Install Chrome
        uses: logikal-io/install-chrome@v1.0.1
        with:
          version: '127.0.6533.72-1'
      - name: test
        run: npm run test 
          
