name: ci_test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: get dependencies
        run: 'npm i --silent'
      - name: Install Chrome
        run: sudo apt-get install -y libnss3-dev libgconf-2-4
      - name: build
        run: npm run build
      - name: check dist folder
        run: ls ./dist
  create-artifact:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          # Artifact name
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: ./dist

          
  
      
          
