name: ci_test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: test
        run: 'npm i --silent'
      - name: Install Chrome
        run: sudo apt-get install -y libnss3-dev libgconf-2-4
      - name: test
        run: npx ng test --watch=false 
          
