name: Second action

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: first_artifact.txt
    steps:
      - name: create_artifact
        shell: bash
        run: |
          echo 'THE FIRST ARTIFACT' > ${{env.ARTIFACT_NAME}}
          ls -l ${{env.ARTIFACT_NAME}}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_NAME}}

      - name: print_date
        run: 'date +"Today is %A, %B %d, %Y. The current time is %H:%M:%S."'

